### PR TITLE
Fix Eq for monid coproducts + introduce semigroup coproducts

### LINKED ISSUE #50: Why is Data.Monoid.Coproduct the semi-direct product?
The documentation for the lazy version says

> m :+: n is the coproduct of monoids m and n. Values of type m :+: n consist of alternating lists of m and n values.

That much is true, in the internal presentation, but there is no way to actually access this structure. Specifically there should be a Bifoldable instance, to make good on the universal property of the coproduct:

> For all monoid homomorphisms *f₁ :: M₁ → M, f₂ :: M₂ → M* there is a unique monoid homomorphism *bifoldMap f₁ f₂ :: M₁ :+: M₂ → M*, such that *bifoldMap f₁ f₂ . inL = f₁* and *bifoldMap f₁ f₂ . inR = f₂*.

Instead the only way to get anything out of *M₁ :+: M₂* is *untangle*, which as far as I can tell just maps the coproduct to the semidirect product *M₁ ⋉ M₂*. Moreover the strict version already does this reduction directly.

But there already is Data.Monoid.SemiDirectProduct, which seems to be the same thing, but with it's variables flipped, slightly different presentation, constraints and function names.

Am I missing something? Is Data.Monoid.Coproduct the coproduct in some other category than the category of monoids? Is there a difference between Data.Monoid.Coproduct and Data.Monoid.SemiDirectProduct that I missed?

### LINKED ISSUE #60: Semigroup Coproduct and Monoid Coproduct are Different
The coproduct in the category of semigroups and he category of monoids are _not_ the same. Here is a textbook example. Consider the trivial monoid whose only element is its identity. The coproduct of this monoid with itself is again the trivial monoid. On the other hand if you view it as a semigroup and compute the coproduct in the category of semigroups you get an infinite semigroup.

Looking at the api, specifically the `Eq` instance, the library seems to be designed under the assumption that coproducts in the category of monoids and the category of semigroups have the same carrier set. Looking at the implementation, the monoid instance on `m1 :+: m2` computes the coproduct of `m1` and `m2` as semigroups and adds a new element as identity to turn it into a monoid. Thus there is no way to construct coproducts using the library, neither for semigroups nor for monoids.

I am not sure if it is wise to design an essentially new library with two products, one for monoids one for semigroups at this point. Though I think that would be the ideal solution. On the other hand I do not have a better idea since I am not sure about the downstream effects of breaking changes.

### PR DESCRIPTION
**Pull request by sonatsuer**
Resolves the issues raised in https://github.com/diagrams/monoid-extras/issues/60 and also refactors a few existing functions.

**Breaking Changes** 
1. The `Eq` instance on `m :+: n` now requires both `m` and `n` to be monoids. The implementation also changed: previously `inL mempty == mempty` evaluated to `False`, now it evaluates to `True`.

**Additions** 
1. Semigroup coproducts are introduced as a new module.
2. The copairing map (the universal map in the coproduct definition) is implemented and exposed for both kinds of coproducts.
3. A new version of `untangle` is implemented (`untangleSemi`) as a monoid homorphism from the coproduct to the semidirect product. This also gave a conceptually clean specification for `untangle`.
4. A more aggressive version of `toAltList` is implemented (`toReducedAltList`). This version also removes identities.
5. Implemented `toMonoid` which is a canonical map from the semigroup coproduct to the monoid coproduct. [Here](https://github.com/diagrams/monoid-extras/issues/60#issuecomment-2822238121) @byorgey  mentions a map in the opposite direction but such a map does not exist in general.

**Refactors**
1. Used `cop` in functions `killL` and `killR`.
2. Used `cop` in the `Action` instance for `(Action m r, Action n r) => Action (m :+: n) r`
3. Implemented `untangle` as an unwrapped version of `untangleSemi`

I think it is important to fix the `Eq` instance and have the `cop` functions exposed as copairing is the whole point of the coproduct definition. I do not have a strong opinion about the rest, especially the refactors.

### CODE REVIEW

**Comment by byorgey** [comment]
Thanks!  I plan to take a close look at this soon.

Hmm, looks like the CI needs to be fixed, I'll take care of that.

**Comment by byorgey** [comment]
@sonatsuer I think I've fixed the CI, can you try merging the current `main` branch into your PR or rebasing on top of it?

**Comment by sonatsuer** [comment]
> What do you think about just getting rid of `Data.Monoid.Coproduct.Strict` at the same time? As you pointed out, it's not correct, and I really don't think anyone is using it.

Sure, I can remove it. If we agree on the Bifoldable instance, then the only other change is an update of the Haddock comments (both for monoids and semigroups) about well-definedness, correct?

File: src/Data/Monoid/Coproduct.hs [hunk 1]
```diff
@@ -58,11 +68,26 @@ normalize = \case
...
 -- For efficiency and simplicity, we implement it just as [Either m
 -- n]: of course, this does not preserve the invariant of strictly
 -- alternating types, but it doesn't really matter as long as we don't
 -- let anyone inspect the internal representation.
 
+-- | Universal map of the coproduct. Both functions in the signature
+--   should be monoid homomorphisms. The name @cop@ is an abbreviation
+--   for copairing.
+cop :: Monoid k => (m -> k) -> (n -> k) -> (m :+: n) -> k
+f `cop` g = foldMap (either f g) . unMCo
```
[the remark this answers is not in the document]
Comment (byorgey) [reply src/Data/Monoid/Coproduct.hs:89]: Ah, that's a good point.  So perhaps we can  add a short comment to the documentation for `cop` explaining why we don't have a Bifoldable instance.

File: src/Data/Monoid/Coproduct.hs [hunk 2]
```diff
@@ -58,11 +68,30 @@ normalize = \case
   []  -> []
   (e:es) -> e : normalize es
 
+
+-- Similar to @normalize@. In additin to combining consecutive values of the same
```
Comment (byorgey) [inline src/Data/Monoid/Coproduct.hs:72]:
```suggestion
-- Similar to @normalize@. In addition to combining consecutive values of the same
```

File: src/Data/Monoid/Coproduct.hs [hunk 3]
```diff
@@ -58,11 +68,30 @@ normalize = \case
...
+    nonIdentity e = e /= Left mempty && e /= Right mempty
+
 -- For efficiency and simplicity, we implement it just as [Either m
 -- n]: of course, this does not preserve the invariant of strictly
 -- alternating types, but it doesn't really matter as long as we don't
 -- let anyone inspect the internal representation.
 
+-- | Universal map of the coproduct. The name @cop@ is an abbreviation
+--   for copairing. Both functions in the signature should be monoid
+--   homomorphisms. If they are general functions then tha coparining may
```
Comment (byorgey) [inline src/Data/Monoid/Coproduct.hs:87]:
```suggestion
--   homomorphisms. If they are general functions then the copairing may
```

File: src/Data/Semigroup/Coproduct.hs [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+normalize = \case
+  Left e1 :| Left e2 : es -> normalize (Left (e1 <> e2) :| es)
+  Right e1 :| Right e2 : es -> normalize (Right (e1 <> e2) :| es)
+  e1 :| es1 -> case es1 of
+    e2 : es2 -> (e1 :| []) <> normalize (e2 :| es2)
+    [] -> e1 :| []
+
+-- | Universal map of the coproduct. The name @cop@ is an abbreviation
+--   for copairing. Both functions in the signature should be semigroup
+--   homomorphisms. If they are general functions then tha coparining may
```
Comment (byorgey) [inline src/Data/Semigroup/Coproduct.hs:53]:
```suggestion
--   homomorphisms. If they are general functions then the copairing may
```

**Review by byorgey — APPROVED** [review]
Great, thanks!  Just a few typos that I noticed.

**Comment by sonatsuer** [comment]
> Great, thanks! Just a few typos that I noticed.

Argh! Sorry, fixed.

**Comment by byorgey** [comment]
> Argh! Sorry, fixed.

No worries!

**Comment by byorgey** [comment]
Released to Hackage as `monoid-extras-0.7`!
